### ISSUE TITLE
support credentials in CORS requests

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/sifttt#19]
From @danhalliday:

The API returns `Access-Control-Allow-Origin: *`, which does not work for credentialed CORS requests.

(Unfortunately we must use credentialed AJAX because the main API’s authentication is (at least, for now) mediated via cookies and cookie sending between domains requires credentialed calls).

For credentialed requests, the `Access-Control-Allow-Origin` header in the server’s response must echo the request’s origin (eg. `Access-Control-Allow-Origin: dashboard.staging.dashaudio.co`).

**Comment by markbirbeck** [comment]
Great idea. Only comment would be to have an option to control this, which is in turn read from an environment variable.

**Comment by danhalliday** [comment]
Cool, I'll sort that probably on Monday.
